### ISSUE TITLE
[Feature Request] Enhancement "Close Graph when present" suggestion

### ISSUE THREAD

**Issue by yiuchungcheung** [info442-sp21/b-team#45]
description of the requested feature: Hoping users wouldn't need to close the existing graph in order to look at other states
explanation for why it would be useful: It isn't really intuitive as users would just want to browse around and check out graphs for different states quickly, so it doesn't really make sense if they have to open, close, click on another state, close, repeat. It would be much more intuitive and straightforward if you guys could remove the closing step!

**Comment by RaphaelKyle** [comment]
Thank you for reporting this. We will work on being able to select whatever state you want without the need to close the graph first.

**Comment by jordanjones243** [comment]
Close Graph when Present button removed, users can now click on any state and the graph will automatically change.
