### ISSUE TITLE
[Minor Bug] Hate Crimes and About Page Linked to Same Page

### ISSUE THREAD

**Issue by juliashull** [info442-sp21/b-team#47]
When clicking on the navigation bar, the "Hate Crimes" tab and the "About" tab go to the same exact page.

Environment encountered: Chrome on a Windows computer

1. Click on "Hate Crimes" tab
2. Click on "About" tab

Actual result = page refreshes but content still the same

Expected result = a new page to pop up with different content for the specified page

**Comment by RaphaelKyle** [comment]
Good catch Julia! You're right this is redundant. We'll be deleting the About page button.

**Comment by RaphaelKyle** [comment]
Done!
