### ISSUE TITLE
[Minor Bug] Map Selector not Working

### ISSUE THREAD

**Issue by juliashull** [info442-sp21/b-team#48]
Major

When hovering over the map when first clicking to the interactive map page the states' color changes and I can click on one state. If I  try to click on a another state it does not allow me too and therefore I am unable to select a specific state to see the hate crime data. After closing the map, I can then click on a state - but I have to close the map again if I want to click to a different state.

Environment it was encountered in = Chrome on a Windows computer

1. Click to Interactive Map page
2. Click on State
3. Try to Click on another State
4. Click "Close Map"
5. Click a new state
6. Try to click on another state

Actual result = stays on originally clicked state until closing the map again
Expected result = be able to click on any state when wanted

**Comment by RaphaelKyle** [comment]
I think this is a minor bug and have also been a feature request. We will work on being able to click any state wanted without the need for the close button.

**Comment by cherimarie** [comment]
Agreed that this is a minor bug- the graph functionality does work for all states, it just requires the graph being closed between.
