### ISSUE TITLE
Map does not show statistics [Major]

### ISSUE THREAD

**Issue by sienasc** [info442-sp21/b-team#49]
Describe the bug
On the "Interactive Map Page", it tells you to click on a state to see statistics, but nothing happens.

To Reproduce

Go to 'https://info442-sp21.github.io/b-team/about.html'
Navigate to "Interactive Map"
Click on any state
You'll see nothing happens

Desktop (please complete the following information):

OS: iOS 11.2.1
Browser: Safari
Version: Version 14.0.3 (16610.4.3.1.4)

**Comment by jordanjones243** [comment]
Interactive map is functional.

**Comment by cherimarie** [comment]
This may be a minor usability bug. When clicking on map, the graph appears underneath it, which is not visible on many screens (including my laptop). It's not unreasonable for a user to think there's nothing happening.
