### ISSUE TITLE
Have to refresh to view new state's graph [minor]

### ISSUE THREAD

**Issue by abq14** [info442-sp21/b-team#50]
Description: When I click on a state, I see that state's graph, but then when I click on a new state, it won't load that state's graph. I have to refresh to see another state's graph. 

Environment: MacOS Big Sur ver 11.2.3, Google Chrome Version 90.0.4430.212

Steps to reproduce: 
1. Go to Interactive Maps page 
2. Click on "Washington" on map 
3. See graph 
4. Click on another state (e.g. "Nevada") 
5. Graph for Nevada doesn't show up 

Expected result: graph for Nevada shows up
Actual result: graph for Washington is still up

**Comment by kristina-te** [comment]
Looked at requirements and saw that this was actually a design issue. However, to add on to this, I believe it should at least give feedback when another state is clicked on, or it should not let the user click on another state until the “Close Graph When Present” is clicked on.

**Comment by RaphaelKyle** [comment]
Thank you for catching this. Julia was the first person to report this issue. It's been reported as a minor bug and has been requested by others as a feature. https://github.com/info442-sp21/b-team/issues/48
