### ISSUE TITLE
[Minor] Cannot reopen graph on mobile device

### ISSUE THREAD

**Issue by tichx** [info442-sp21/b-team#53]
**Describe the bug**
The graph on the map page does not have option to reopen the graph

**Severity**
Minor

**To Reproduce**
1. Hit the hamburger menu
2. Choose the interactive map tab
3. scroll down to the statistical graph section

**Expected behavior**
After close the graph, it should have the button turned to open the graph, otherwise, users would not be able to see the graph.

**Current behavior**
After close the graph, the entire graph section is gone with no instruction on how to turn it back on

**Screenshots**
![IMG_B702B358C78A-1](https://user-images.githubusercontent.com/12144060/119570090-7d35f700-bd64-11eb-83fa-dd349182c6b9.jpeg)

**Desktop (please complete the following information):**
* Device: iPhone 12 XSMax 
* OS: iOS 12
* Browser: Safari
* Version: 14.0

**Comment by RaphaelKyle** [comment]
Thank you for reporting this. We will work on it. We do think that this is a duplicate report to this post. https://github.com/info442-sp21/b-team/issues/52
