### ISSUE TITLE
Having to close graph to display a new graph [minor]

### ISSUE THREAD

**Issue by diegot-stack** [info442-sp21/b-team#54]
![Screen Shot 2021-05-25 at 2 15 01 PM](https://user-images.githubusercontent.com/56012534/119569652-e406e080-bd63-11eb-8bda-4f259c5d7e75.png)
![Screen Shot 2021-05-25 at 2 15 16 PM](https://user-images.githubusercontent.com/56012534/119569658-e6693a80-bd63-11eb-886f-68102f24fc52.png)

After clicking on a state to see the graph, you have to click the "close graph when you present" to have the new visualization pop up. 

Steps to recreate: 
1. Click on a state
2. Without closing the visualizations click on another state

Environment: Desktop, Chrome (Version 90.0.4430.212) on macOS Mojave

**Comment by RaphaelKyle** [comment]
Thank you for catching this. Julia was the first person to report this issue. It's been reported as a minor bug and has been requested by others as a feature. https://github.com/info442-sp21/b-team/issues/48
