### ISSUE TITLE
[Feature Request] Change colors of map to show states with highest and lowest hate crime

### ISSUE THREAD

**Issue by drishtividyarthi** [info442-sp21/b-team#55]
One idea would be to make states on the map different colors, probably a gradient from dark to light, to show which states have the highest and lowest hate crime rates. You could either add a second map like this to the existing page with visualizations or simply change the existing map to have different colors.

I think this would allow the users to compare hate crime rates more easily between states as the visualization would be easier to understand. Also by seeing the color changes on the map, the visualization can lead the user more clearly on which states they should be selecting to see more specific statistics. For example if they want to see states with the highest hate crimes they'll already know which ones to select instead of having to guess or play around with the platform.  
<img width="830" alt="Screen Shot 2021-05-25 at 2 23 39 PM" src="https://user-images.githubusercontent.com/55815122/119570344-d736bc80-bd64-11eb-8dc7-c3da4763c070.png">

**Comment by RaphaelKyle** [comment]
Thank you for suggesting this. We have a heat map as one of our stretch goals, and we will be taking this into consideration. We will try to implement this if we have time.

**Comment by jordanjones243** [comment]
Heat map with map legend implemented.
