### ISSUE TITLE
[Feature Request] Articles based on state. 

### ISSUE THREAD

**Issue by kristina-te** [info442-sp21/b-team#58]
Help users understand the context of the number of hate crimes in each state by attaching articles associated with that state selected. There is a news tab that is generalized, but I think it might be better if it could be directly linked to the visualization to help users make stronger connections.

**Comment by RaphaelKyle** [comment]
Thank you for suggesting this. This is a great idea. I will pass this on to our developer in charge of the News section and see if he has time to implement this.
