### ISSUE TITLE
Graph does not automatically update when a new state is selected

### ISSUE THREAD

**Issue by ashshah1** [info442-sp21/b-team#59]
To refresh the statistics view, you have to refresh or close the graph and click a new state

I'd recommend either including some instruction that says you need to do that to update the graph or changing the implementation so it automatically updates

<img width="1408" alt="Screen Shot 2021-05-25 at 2 42 23 PM" src="https://user-images.githubusercontent.com/55997736/119572346-6c3ab500-bd67-11eb-9094-3749f68772d7.png">

**Comment by RaphaelKyle** [comment]
Thank you for catching this. Julia was the first person to report this issue. It's been reported as a minor bug and has been requested by others as a feature. https://github.com/info442-sp21/b-team/issues/48
