### ISSUE TITLE
[Feature Request] Using another article source other than RSS

### ISSUE THREAD

**Issue by ifrahm** [info442-sp21/b-team#60]
The RSS app creates a nice look of the news page and works as intended. However, when the user selects the article, there is a 8 second wait before the article is visible. If there is another way to have the same feature but avoid that it would create a smoother user experience.

**Comment by RaphaelKyle** [comment]
Great suggestion. I will pass this on to our developer in charge of the News section to see if there are any workarounds to the 8-second timer.
