### ISSUE TITLE
[Feature Request] Call to Action Page/Section

### ISSUE THREAD

**Issue by drishtividyarthi** [info442-sp21/b-team#62]
Since this is a project on a major social issue, it might be useful to add a page on what the user can do if they want to help the issue or work towards ending the issue. **This page could also have resources and links to other organizations that the user could check it out if they want to help or be more involved.**

Including this page would encourage people to take the information they are learning and take physical action or do something that will help the issue. It would become a good combination of informing the user and also encouraging them to do what they can to help.

**Comment by RaphaelKyle** [comment]
Thank you for suggesting this. This is a great idea. We will try and add a call to action section at the bottom of our About page if we have time.
