### ISSUE TITLE
[Feature Request] Add Auto Scroll When Clicking on a State

### ISSUE THREAD

**Issue by popi1141** [info442-sp21/b-team#64]
Quick minor thing, but it'd be great to auto scroll the user down to the graph area when they select a state. Right now, I wouldn't know a graph has been loaded until I scroll down.

Currrently on Windows 10 desktop.

![image](https://user-images.githubusercontent.com/45519338/119577992-3db3ed00-bdee-11eb-8ce9-aacb4a719f42.png)

**Comment by RaphaelKyle** [comment]
Great suggestion! We will see what we can do about this.
