### ISSUE TITLE
[Feature Request] News Page Enhancement

### ISSUE THREAD

**Issue by gidchia** [info442-sp21/b-team#65]
**Describe the enhancement**
Would be nice to have a carousel of news articles that a user can scroll through. Might be overwhelming to a user to see all the articles on the same page.

**To Reproduce**

1. Go to https://info442-sp21.github.io/b-team/
2. Click on "News"

**Desktop (please complete the following information):**

OS: iOS
Browser - Chrome
Version - Version 90.0.4430.85

**Comment by RaphaelKyle** [comment]
Thank you for the design suggestion. We will check in with our designer and take this into consideration.
