### ISSUE TITLE
[Feature Request] Map doesn't scale (Alternative)

### ISSUE THREAD

**Issue by gidchia** [info442-sp21/b-team#66]
**Describe the enhancement**
Given that the map doesn't scale to a mobile device, and too small a map on a mobile device would be difficult to interact with, it might be nice to have the map be swapped out for a list of states in the mobile version.

**To Reproduce**

1. Access https://info442-sp21.github.io/b-team/ on a Mobile Device
2. Click on "Interactive Map"

**Mobile Device (please complete the following information):**
Phone: iPhone X
OS: iOS
Browser - Safari

**Comment by RaphaelKyle** [comment]
Thank you for the alternative suggestion! We will look into it.

**Comment by cherimarie** [comment]
This is a great idea! It's easy to think of "responsive design" as just making things larger or smaller to fit the screen, but the best responsive sites tailor information format for different access types.
