### ISSUE TITLE
[Feature Request] Landing Page

### ISSUE THREAD

**Issue by gidchia** [info442-sp21/b-team#67]
**Describe the enhancement**
It might be nice to have a well-defined landing page, separate from the "About" Page. As a user, I would expect to be brought to the "Home" page by clicking on the "Hate Crimes" logo. 

**To Reproduce**

1. Go to https://info442-sp21.github.io/b-team/

**Desktop (please complete the following information):**

OS: iOS
Browser - Chrome
Version - Version 90.0.4430.85

**Comment by RaphaelKyle** [comment]
Thank you for suggesting this. We will see if we have time to implement this.
