### ISSUE TITLE
[Feature Request] Use of Overlays

### ISSUE THREAD

**Issue by gidchia** [info442-sp21/b-team#68]
**Describe the enhancement**
Would be nice to see an overlay over the cover photo - the word "About" fades into the cover photo. Overlaying the image with a translucent screen of 50% transparency could help the word "Pop" more.

**To Reproduce**
1. Go to https://info442-sp21.github.io/b-team/

**Desktop (please complete the following information):**

OS: iOS
Browser - Chrome
Version - Version 90.0.4430.85

**Comment by RaphaelKyle** [comment]
Done!
